server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Charming-Victim/springcloud.git/
          search-paths: config
          username: 842721197@qq.com
          password: abc123..ou
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/